[tool.commitizen]
name = "cz_conventional_commits"
tag_format = "v$version"
version_scheme = "semver"
version_provider = "commitizen"
version = "0.31.0"
update_changelog_on_bump = false
major_version_zero = true
version_files = [
    "crates/lonko/Cargo.toml",
    "crates/lonko-hook/Cargo.toml",
]
