#!/usr/bin/env bash
set -euo pipefail

REPO="$(cd "$(dirname "$0")" && pwd)"

echo "==> Building shepherd..."
cargo install --path "$REPO/crates/shepherd" --quiet
cargo install --path "$REPO/crates/shepherd-hook" --quiet
echo "    shepherd and shepherd-hook installed to ~/.cargo/bin/"

echo ""
echo "==> Installing tmux scripts..."
TMUX_SCRIPTS_DIR="$HOME/.config/tmux/scripts"
mkdir -p "$TMUX_SCRIPTS_DIR"
for script in "$REPO/scripts/"*.sh; do
    install -m 0755 "$script" "$TMUX_SCRIPTS_DIR/"
    echo "    $(basename "$script") → $TMUX_SCRIPTS_DIR/"
done

echo ""
echo "==> Generating tmux config fragment..."
TMUX_CONFIG="$HOME/.config/tmux/shepherd.conf"
cat > "$TMUX_CONFIG" <<'TMUX_EOF'
# Shepherd tmux integration
# Auto-generated by shepherd install.sh — DO NOT EDIT BY HAND
# Source this file from your tmux.conf (after any global hooks):
#   if-shell "[ -f ~/.config/tmux/shepherd.conf ]" "source-file ~/.config/tmux/shepherd.conf"

# Auto-follow shepherd between windows/sessions
set-hook -ga client-session-changed 'run-shell "~/.config/tmux/scripts/shepherd-follow.sh"'
set-hook -ga after-select-window    'run-shell "~/.config/tmux/scripts/shepherd-follow.sh"'

# Panel toggle: prefix + s
bind s run-shell "~/.config/tmux/scripts/shepherd-panel.sh"

# Panel direct tabs via terminal escape sequences (e.g. Ghostty Cmd+Shift+A/S)
set -s user-keys[22] "\e[sa"
set -s user-keys[23] "\e[ss"
bind -n User22 run-shell "~/.config/tmux/scripts/shepherd-panel.sh agents"
bind -n User23 run-shell "~/.config/tmux/scripts/shepherd-panel.sh sessions"

# Permission responses from any pane (e.g. Ghostty Cmd+Shift+Y/N/W)
# Talks to the running shepherd over its Unix socket, so the panel
# doesn't need to be visible or focused.
set -s user-keys[24] "\e[sy"
set -s user-keys[25] "\e[sn"
set -s user-keys[26] "\e[sw"
bind -n User24 run-shell "shepherd respond y"
bind -n User25 run-shell "shepherd respond n"
bind -n User26 run-shell "shepherd respond w"
TMUX_EOF
echo "    $TMUX_CONFIG"

echo ""
echo "==> Installing hooks..."
shepherd --install-hooks
