#!/usr/bin/env bash
set -euo pipefail

REPO="$(cd "$(dirname "$0")" && pwd)"

echo "==> Building lonko..."
cargo install --path "$REPO/crates/lonko" --quiet
cargo install --path "$REPO/crates/lonko-hook" --quiet
echo "    lonko and lonko-hook installed to ~/.cargo/bin/"

echo ""
echo "==> Installing tmux scripts..."
TMUX_SCRIPTS_DIR="$HOME/.config/tmux/scripts"
mkdir -p "$TMUX_SCRIPTS_DIR"
for script in "$REPO/scripts/"*.sh; do
    install -m 0755 "$script" "$TMUX_SCRIPTS_DIR/"
    echo "    $(basename "$script") → $TMUX_SCRIPTS_DIR/"
done

echo ""
echo "==> Generating tmux config fragment..."
TMUX_CONFIG="$HOME/.config/tmux/lonko.conf"
cat > "$TMUX_CONFIG" <<'TMUX_EOF'
# Lonko tmux integration
# Auto-generated by lonko install.sh — DO NOT EDIT BY HAND
# Source this file from your tmux.conf (after any global hooks):
#   if-shell "[ -f ~/.config/tmux/lonko.conf ]" "source-file ~/.config/tmux/lonko.conf"

# Auto-follow lonko between windows/sessions
set-hook -ga client-session-changed 'run-shell "~/.config/tmux/scripts/lonko-follow.sh"'
set-hook -ga after-select-window    'run-shell "~/.config/tmux/scripts/lonko-follow.sh"'

# Panel toggle: prefix + s
bind s run-shell "~/.config/tmux/scripts/lonko-panel.sh"

# Panel direct tabs via terminal escape sequences (e.g. Ghostty Cmd+Shift+A/S)
set -s user-keys[22] "\e[sa"
set -s user-keys[23] "\e[ss"
bind -n User22 run-shell "~/.config/tmux/scripts/lonko-panel.sh agents"
bind -n User23 run-shell "~/.config/tmux/scripts/lonko-panel.sh sessions"

# Permission responses from any pane (e.g. Ghostty Cmd+Shift+Y/N/W)
# Talks to the running lonko over its Unix socket, so the panel
# doesn't need to be visible or focused.
set -s user-keys[24] "\e[sy"
set -s user-keys[25] "\e[sn"
set -s user-keys[26] "\e[sw"
bind -n User24 run-shell "lonko respond y"
bind -n User25 run-shell "lonko respond n"
bind -n User26 run-shell "lonko respond w"
TMUX_EOF
echo "    $TMUX_CONFIG"

echo ""
echo "==> Installing hooks..."
lonko --install-hooks
